name: Deploy MkDocs

on:
  push:
    branches:
      - main   # Change to "master" if your repo’s default branch is named master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install mkdocs-material pymdown-extensions

      - name: Deploy to GitHub Pages
        run: mkdocs gh-deploy --force
